"""sprint3_workers_and_documents

Revision ID: 6a4538e0bc90
Revises: 90bb59a72beb
Create Date: 2026-08-07 19:15:25.700932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4538e0bc90'
down_revision: Union[str, Sequence[str], None] = '90bb59a72beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('employee_code', sa.String(length=50), nullable=False, comment='Org-unique identifier printed on muster rolls, e.g. W-001'),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=50), nullable=False, comment='One of WorkerTrade constants'),
    sa.Column('skill_level', sa.String(length=20), nullable=False, comment='One of SkillLevel constants'),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('daily_wage_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='Base daily wage in INR — Numeric avoids float rounding'),
    sa.Column('pf_account_number', sa.String(length=50), nullable=True, comment='Provident Fund account number'),
    sa.Column('esi_number', sa.String(length=50), nullable=True, comment='Employee State Insurance number'),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=True, comment='User who first registered this worker'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Tenant scoping — every query must filter by this'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last modified this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_is_deleted'), 'workers', ['is_deleted'], unique=False)
    op.create_index('ix_workers_org_active', 'workers', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_workers_org_code', 'workers', ['organization_id', 'employee_code'], unique=True)
    op.create_index('ix_workers_org_deleted', 'workers', ['organization_id', 'is_deleted'], unique=False)
    op.create_index('ix_workers_org_trade', 'workers', ['organization_id', 'trade'], unique=False)
    op.create_index(op.f('ix_workers_organization_id'), 'workers', ['organization_id'], unique=False)
    op.create_table('worker_documents',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='One of DocumentType constants'),
    sa.Column('document_number', sa.String(length=100), nullable=True, comment='Aadhaar number, PAN number, Labour Card number, etc.'),
    sa.Column('file_key', sa.String(length=500), nullable=True, comment='S3/MinIO object key — null until Sprint 6 populates it'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='Original filename shown to the user'),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Tenant scoping — every query must filter by this'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last modified this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_docs_deleted', 'worker_documents', ['organization_id', 'is_deleted'], unique=False)
    op.create_index('ix_worker_docs_org_type', 'worker_documents', ['organization_id', 'document_type'], unique=False)
    op.create_index('ix_worker_docs_org_worker', 'worker_documents', ['organization_id', 'worker_id'], unique=False)
    op.create_index(op.f('ix_worker_documents_is_deleted'), 'worker_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_worker_documents_organization_id'), 'worker_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_worker_documents_worker_id'), 'worker_documents', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_documents_worker_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_organization_id'), table_name='worker_documents')
    op.drop_index(op.f('ix_worker_documents_is_deleted'), table_name='worker_documents')
    op.drop_index('ix_worker_docs_org_worker', table_name='worker_documents')
    op.drop_index('ix_worker_docs_org_type', table_name='worker_documents')
    op.drop_index('ix_worker_docs_deleted', table_name='worker_documents')
    op.drop_table('worker_documents')
    op.drop_index(op.f('ix_workers_organization_id'), table_name='workers')
    op.drop_index('ix_workers_org_trade', table_name='workers')
    op.drop_index('ix_workers_org_deleted', table_name='workers')
    op.drop_index('ix_workers_org_code', table_name='workers')
    op.drop_index('ix_workers_org_active', table_name='workers')
    op.drop_index(op.f('ix_workers_is_deleted'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
