"""sprint2_user_softdelete_invitations_projects_sites

Revision ID: 90bb59a72beb
Revises: 983fae5dc81d
Create Date: 2026-08-01 17:10:06.160628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bb59a72beb'
down_revision: Union[str, Sequence[str], None] = '983fae5dc81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Email address the invitation was sent to'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Role the invitee will receive upon acceptance'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw token — never store raw token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the invitee accepts; NULL means still pending'),
    sa.Column('invited_by_id', sa.UUID(), nullable=False, comment='Admin who created this invitation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Short identifier unique within the org, e.g. HYD-001'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True, comment='Set when project transitions to closed'),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True, comment='Total approved budget in INR'),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Tenant scoping — every query must filter by this'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last modified this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index('ix_projects_org_code', 'projects', ['organization_id', 'code'], unique=True)
    op.create_index('ix_projects_org_deleted', 'projects', ['organization_id', 'is_deleted'], unique=False)
    op.create_index('ix_projects_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_project_manager_id'), 'projects', ['project_manager_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('sites',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('site_engineer_id', sa.UUID(), nullable=True, comment='Primary site engineer responsible for this site'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Tenant scoping — every query must filter by this'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last modified this record'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_engineer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_is_deleted'), 'sites', ['is_deleted'], unique=False)
    op.create_index('ix_sites_org_deleted', 'sites', ['organization_id', 'is_deleted'], unique=False)
    op.create_index('ix_sites_org_project', 'sites', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_index(op.f('ix_sites_site_engineer_id'), 'sites', ['site_engineer_id'], unique=False)
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID of the admin who created this account (None for first admin)'))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_index(op.f('ix_sites_site_engineer_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_index('ix_sites_org_project', table_name='sites')
    op.drop_index('ix_sites_org_deleted', table_name='sites')
    op.drop_index(op.f('ix_sites_is_deleted'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index('ix_projects_org_status', table_name='projects')
    op.drop_index('ix_projects_org_deleted', table_name='projects')
    op.drop_index('ix_projects_org_code', table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
